
import type { Task } from '@/lib/types';
import { add, sub, startOfToday } from 'date-fns';

export const getInitialTasks = (): Task[] => [
    {
        id: '1',
        title: 'Finalize Q3 marketing strategy',
        description: 'Review and approve the final draft of the Q3 marketing plan.',
        dueDate: add(new Date(), { days: 3 }),
        startTime: '10:00',
        endTime: '11:00',
        priority: 'high',
        status: 'active',
        category: 'Work',
        createdAt: sub(new Date(), { days: 2 }),
        projectId: '1',
      },
      {
        id: '2',
        title: 'Develop new landing page design',
        description: 'Create mockups and prototypes for the new homepage.',
        dueDate: add(new Date(), { days: 7 }),
        priority: 'urgent',
        status: 'in-progress',
        category: 'Work',
        createdAt: sub(new Date(), { days: 1 }),
        projectId: '1',
      },
      {
        id: '3',
        title: 'Onboard new marketing intern',
        description: 'Prepare onboarding materials and schedule intro meetings.',
        dueDate: add(new Date(), { days: 1 }),
        priority: 'medium',
        status: 'completed',
        category: 'Work',
        completionDate: new Date(),
        createdAt: sub(new Date(), { days: 5 }),
        projectId: '1',
      },
      {
        id: '4',
        title: 'Plan team offsite event',
        description: 'Coordinate logistics, activities, and budget for the upcoming team offsite.',
        dueDate: add(new Date(), { days: 14 }),
        priority: 'medium',
        status: 'active',
        category: 'Work',
        createdAt: sub(new Date(), { days: 10 }),
        parentId: '1',
        projectId: '1',
      },
      {
        id: '5',
        title: 'Fix login issue on mobile app',
        description: 'Investigate and resolve the reported login bug on iOS and Android.',
        dueDate: sub(new Date(), { days: 1 }),
        priority: 'high',
        status: 'active',
        category: 'Work',
        createdAt: new Date(),
        projectId: '1',
      },
      {
        id: '6',
        title: 'Update customer support documentation',
        description: 'Add new section for the latest feature release.',
        priority: 'low',
        status: 'completed',
        category: 'Learning',
        completionDate: sub(new Date(), { days: 3 }),
        createdAt: sub(new Date(), { days: 8 }),
        projectId: '1',
      },
      {
        id: '7',
        title: 'Call with the legal team',
        description: 'Discuss the new privacy policy updates.',
        dueDate: add(startOfToday(), { hours: 15 }),
        startTime: '15:00',
        endTime: '15:30',
        priority: 'urgent',
        status: 'active',
        category: 'Work',
        createdAt: sub(new Date(), { days: 1 }),
        projectId: '1',
      },
       {
        id: '8',
        title: 'Refactor legacy code',
        description: 'Initial plan was to refactor, but we decided to rewrite from scratch.',
        priority: 'low',
        status: 'canceled',
        category: 'Work',
        cancellationNote: 'Decided to rewrite the module instead of refactoring.',
        createdAt: sub(new Date(), { days: 12 }),
        projectId: '1',
      },
       {
        id: '9',
        title: 'Weekly grocery shopping',
        description: 'Buy vegetables, fruits, and other essentials.',
        priority: 'medium',
        status: 'on-hold',
        category: 'Chore',
        dueDate: add(new Date(), { days: 2 }),
        createdAt: new Date(),
        projectId: '1',
      },
      {
        id: '10',
        title: 'Read a chapter of "Sapiens"',
        description: 'Continue reading the book.',
        priority: 'low',
        status: 'active',
        category: 'Personal',
        createdAt: sub(new Date(), { days: 1 }),
        projectId: '1',
      },
       {
        id: '11',
        title: 'Follow up on invoice #1234',
        description: 'Sent email, waiting for response from client.',
        priority: 'medium',
        status: 'on-hold',
        category: 'Work',
        createdAt: sub(new Date(), { days: 4 }),
        projectId: '1',
      },
  ];
